### ISSUE TITLE
bin.js missing

### ISSUE THREAD

**Issue by 0x00A** [dominictarr/noderify#10]
npm crashses on install since it can't find `./bin.js` (which should be generated by the `prepublish` script).

**Comment by dominictarr** [comment]
npm is aloof and likes ignoring things so it ignores things in `.gitignore` if it doesn't have an `.npmignore`
which makes sense, right?
luckily I knew that and didn't have to spend several hours debugging.

fixed in 1.1.9

**Comment by 0x00A** [comment]
excellent! closing now then.
