### ISSUE TITLE
Replacement modules

### ISSUE THREAD

**Issue by staltz** [dominictarr/noderify#14]
Is there any current way of replacing some modules like browserify uses the `browser` field in package.json? https://github.com/defunctzombie/package-browser-field-spec

I'm not sure if noderify's current status supports this in one way or another (through a custom prelude?).

**Comment by dominictarr** [comment]
yes, noderify uses a custom assemblage of browserify modules to avoid browserify's inserts. there is also an `--electron` option. we could certainly add a way to configure this.

**Comment by dominictarr** [comment]
or add it as an option if you have a generic one (like, say, `--react-native`)

**Comment by staltz** [comment]
Yeah this is done 👍

**Comment by dominictarr** [comment]
awesome
