### ISSUE TITLE
Cannot read property main of undefined

### ISSUE THREAD

**Issue by staltz** [dominictarr/noderify#17]
This seems to be a noderify issue: https://github.com/staltz/mmmmm-mobile/issues/1

Reproduction comes for free, just clone that repo and run yarn.

**Comment by dominictarr** [comment]
I think this was caused by old version of `resolve` I think this is fixed in `noderify@3.0.2`

**Comment by staltz** [comment]
Oh that explains something. I'll try 3.0.2 and report back

**Comment by staltz** [comment]
Seems solved 👍
