### ISSUE TITLE
Custom prelude option is ignored

### ISSUE THREAD

**Issue by staltz** [dominictarr/noderify#20]
It seems not possible to customize the prelude even though the readme instructs about that possibility. A simple search for "prelude" in this library will show it's not used from `argv`.

I could send a PR to fix that.

**Comment by dominictarr** [comment]
I think things changed a lot since that was added (although I don't remember exactly what, given that it's been a while) do you just want to insert something that is always there or to interact with module loading in some way?
(anyway, PR welcome but you should also give some context about what problem you are trying to solve)

**Comment by staltz** [comment]
Good point about the context. The context is that I'm running noderify to reduce the size of scuttlebot on mobile, and the way that `nodejs-mobile` works means that I would need to prepend `__dirname` (in the context of the noderified `index.js`) in this resolve:

https://github.com/dominictarr/noderify/blob/8f571b2b9258bf8955253b1a756e5cb92649cd76/pack.js#L11

A simple PR for that, without a custom prelude would be:

```js
// ...
    var resolved = require('path').resolve(__dirname ? __dirname : '.', file)
// ...
```

**Comment by dominictarr** [comment]
hmm, so `require('path').resolve(file)` doesn't work? hmm I guess because process.env.CWD isn't present on android or something?
This sounds very reasonable, lets just make it this the default behaviour (since this doesn't impact anything else)

what about `resolve('.', file)`, does that work?

**Comment by staltz** [comment]
I'll try `resolve('.', file)`, but another option is checking with nodejs-mobile can they fix the process.env.CWD so that `resolve('foo')` becomes `./foo` not `/foo`.

**Comment by dominictarr** [comment]
what module is using __dirname?

**Comment by staltz** [comment]
The scuttlebot on mobile index.js which looks for the .ssb folder based on the current folder because nodejs-mobile doesn't support os.homedir() (where as my react-native-node did support).

**Comment by dominictarr** [comment]
@staltz shall we fix this here, or did you post an issue on nodejs-mobile

**Comment by staltz** [comment]
Didn't do it yet but I'll talk to nodejs-mobile folks

**Comment by staltz** [comment]
So, basically the fix should not happen in nodejs-mobile because it runs as a thread in the app, not as a process, so it shares the same `cwd` as the app, which is assigned by the Android OS and is `/` for some reason.

I have two solutions in mind so far:

- prefixing `__dirname` as a PR to noderify
- make the entry point be `loader.js` which hacks `os.homedir()` or `process.cwd()` and then proceeds to require `index.js` (noderified)

**Comment by staltz** [comment]
I went with the second solution, and I think it's better because the real problem is that `process.cwd()` is not set right.

**Comment by dominictarr** [comment]
yup, I think that is a good decision, and also good to know about node-mobile.
